### ISSUE TITLE
NameError: name 'ktps' is not defined

### ISSUE THREAD

**Issue by tobimichigan** [MIPT-Oulu/solt#73]
While testing one of the notebook algorithm, this error occured:
`kpts = None
for annotation_fname in glob.glob(os.path.join('Data', 'helen_annotations', '*.txt')):
    with open(annotation_fname) as f:
        if f.readline()[:-1] == fname.split('.')[0]:
            ktps = []
            for l in f:
                tmp = l.split()
                ktps.append([float(tmp[0]), float(tmp[2])])
            break
kpts = np.array(ktps)`

Specific Error:
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-6-bab710155735> in <module>
      8                 ktps.append([float(tmp[0]), float(tmp[2])])
      9             break
---> 10 kpts = np.array(ktps)

NameError: name 'ktps' is not defined

**Comment by lext** [comment]
Can you show a better formatted code snippet?

**Comment by tobimichigan** [comment]
here u go:
![Screenshot_2020-06-02 Helen_faces - Jupyter Notebook](https://user-images.githubusercontent.com/5084987/83477361-fe78e780-a48a-11ea-914b-a0a91be31d14.png)

**Comment by soupault** [comment]
@tobimichigan the issue does no seem to be related to `solt` in any way. Check the `if` condition in the code - if it is not executed, `ktps` is not defined, thus, the issue.
